// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfNroFVtHZPr9Lc7bgZfKfrM54NwjiLu4',
    appId: '1:377207291354:web:0f287b05cfe2af085bd4e3',
    messagingSenderId: '377207291354',
    projectId: 'valet-app-e4af0',
    authDomain: 'valet-app-e4af0.firebaseapp.com',
    databaseURL: 'https://valet-app-e4af0-default-rtdb.firebaseio.com',
    storageBucket: 'valet-app-e4af0.appspot.com',
    measurementId: 'G-XEV9T1S679',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlcr7kDF4lB4cIBTVQEZ9Tm4k6KNAY-wc',
    appId: '1:377207291354:android:8a33ad271a9a0f255bd4e3',
    messagingSenderId: '377207291354',
    projectId: 'valet-app-e4af0',
    databaseURL: 'https://valet-app-e4af0-default-rtdb.firebaseio.com',
    storageBucket: 'valet-app-e4af0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHqq5rQSutAqocsbhi7I5pqb7WDAID_GY',
    appId: '1:377207291354:ios:5bc58c9cdf19436f5bd4e3',
    messagingSenderId: '377207291354',
    projectId: 'valet-app-e4af0',
    databaseURL: 'https://valet-app-e4af0-default-rtdb.firebaseio.com',
    storageBucket: 'valet-app-e4af0.appspot.com',
    iosBundleId: 'com.example.curbifyValet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHqq5rQSutAqocsbhi7I5pqb7WDAID_GY',
    appId: '1:377207291354:ios:35abaef41fea44875bd4e3',
    messagingSenderId: '377207291354',
    projectId: 'valet-app-e4af0',
    databaseURL: 'https://valet-app-e4af0-default-rtdb.firebaseio.com',
    storageBucket: 'valet-app-e4af0.appspot.com',
    iosBundleId: 'com.example.flutterCurbify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfNroFVtHZPr9Lc7bgZfKfrM54NwjiLu4',
    appId: '1:377207291354:web:968f4a004a393c8a5bd4e3',
    messagingSenderId: '377207291354',
    projectId: 'valet-app-e4af0',
    authDomain: 'valet-app-e4af0.firebaseapp.com',
    databaseURL: 'https://valet-app-e4af0-default-rtdb.firebaseio.com',
    storageBucket: 'valet-app-e4af0.appspot.com',
    measurementId: 'G-96NZX9M0Y6',
  );
}
