name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses

      - name: Build Android APK (release)
        run: bash scripts/build.sh prod

      - name: Build Android AppBundle (release)
        run: flutter build appbundle --release --target=lib/main.dart --dart-define=ENV=prod

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab

  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Set Xcode version
        run: sudo xcode-select -s "/Applications/Xcode.app/Contents/Developer"

      - name: Install CocoaPods dependencies
        working-directory: ios
        run: pod install --repo-update

      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign --target=lib/main.dart --dart-define=ENV=prod

      - name: Upload iOS build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-app
          path: build/ios/iphoneos/*.app